/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl2.parser.antlr.internal.InternalMMLParser;
import org.xtext.example.mydsl2.services.MMLGrammarAccess;

public class MMLParser extends AbstractAntlrParser {

	@Inject
	private MMLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMMLParser createParser(XtextTokenStream stream) {
		return new InternalMMLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Traitement";
	}

	public MMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
