/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl2.ui.internal.Mydsl2Activator;

public class MMLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Mydsl2Activator.getInstance().getInjector("org.xtext.example.mydsl2.MML");
	}

}
