/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl2.MMLRuntimeModule
import org.xtext.example.mydsl2.MMLStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MMLIdeSetup extends MMLStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MMLRuntimeModule, new MMLIdeModule))
	}
	
}
