/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2;

import org.xtext.example.mydsl2.AbstractMMLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MMLRuntimeModule extends AbstractMMLRuntimeModule {
}
