/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.example.mydsl2.ui.AbstractMMLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MMLUiModule extends AbstractMMLUiModule {
  public MMLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
