/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMMLScopeProvider extends DelegatingScopeProvider {
}
