/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Algorithm</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.mML.Algorithm#getLang <em>Lang</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.mML.Algorithm#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.mML.MMLPackage#getAlgorithm()
 * @model
 * @generated
 */
public interface Algorithm extends EObject
{
  /**
   * Returns the value of the '<em><b>Lang</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl2.mML.Lang}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Lang</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lang</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.Lang
   * @see #setLang(Lang)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getAlgorithm_Lang()
   * @model
   * @generated
   */
  Lang getLang();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.Algorithm#getLang <em>Lang</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lang</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.Lang
   * @see #getLang()
   * @generated
   */
  void setLang(Lang value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(EObject)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getAlgorithm_Name()
   * @model containment="true"
   * @generated
   */
  EObject getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.Algorithm#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(EObject value);

} // Algorithm
