/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.mML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl2.mML.MMLFactory
 * @model kind="package"
 * @generated
 */
public interface MMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "mML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl2/MML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "mML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MMLPackage eINSTANCE = org.xtext.example.mydsl2.mML.impl.MMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.TraitementImpl <em>Traitement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.TraitementImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTraitement()
   * @generated
   */
  int TRAITEMENT = 0;

  /**
   * The feature id for the '<em><b>Chemin</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT__CHEMIN = 0;

  /**
   * The feature id for the '<em><b>Eval</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT__EVAL = 1;

  /**
   * The feature id for the '<em><b>Algo</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT__ALGO = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT__NAME = 3;

  /**
   * The feature id for the '<em><b>Names</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT__NAMES = 4;

  /**
   * The number of structural features of the '<em>Traitement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAITEMENT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.VariableImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.AlgorithmImpl <em>Algorithm</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.AlgorithmImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getAlgorithm()
   * @generated
   */
  int ALGORITHM = 2;

  /**
   * The feature id for the '<em><b>Lang</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__LANG = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM__NAME = 1;

  /**
   * The number of structural features of the '<em>Algorithm</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ALGORITHM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.StratEvalImpl <em>Strat Eval</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.StratEvalImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getStratEval()
   * @generated
   */
  int STRAT_EVAL = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT_EVAL__NAME = 0;

  /**
   * The number of structural features of the '<em>Strat Eval</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRAT_EVAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.CrossValidationImpl <em>Cross Validation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.CrossValidationImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getCrossValidation()
   * @generated
   */
  int CROSS_VALIDATION = 4;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_VALIDATION__NUMBER = 0;

  /**
   * The number of structural features of the '<em>Cross Validation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CROSS_VALIDATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.TrainingTestImpl <em>Training Test</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.TrainingTestImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTrainingTest()
   * @generated
   */
  int TRAINING_TEST = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST__NAME = STRAT_EVAL__NAME;

  /**
   * The feature id for the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST__NUMBER = STRAT_EVAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Training Test</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRAINING_TEST_FEATURE_COUNT = STRAT_EVAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.SVMImpl <em>SVM</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.SVMImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVM()
   * @generated
   */
  int SVM = 6;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__TYPE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM__NAME = 1;

  /**
   * The number of structural features of the '<em>SVM</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SVM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.impl.TreeImpl <em>Tree</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.impl.TreeImpl
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTree()
   * @generated
   */
  int TREE = 7;

  /**
   * The feature id for the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE__TYPE = 0;

  /**
   * The number of structural features of the '<em>Tree</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TREE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.Lang <em>Lang</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.Lang
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getLang()
   * @generated
   */
  int LANG = 8;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.SVMKernel <em>SVM Kernel</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.SVMKernel
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVMKernel()
   * @generated
   */
  int SVM_KERNEL = 9;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.SVMType <em>SVM Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.SVMType
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVMType()
   * @generated
   */
  int SVM_TYPE = 10;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl2.mML.Treetype <em>Treetype</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl2.mML.Treetype
   * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTreetype()
   * @generated
   */
  int TREETYPE = 11;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.Traitement <em>Traitement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Traitement</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement
   * @generated
   */
  EClass getTraitement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.Traitement#getChemin <em>Chemin</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chemin</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement#getChemin()
   * @see #getTraitement()
   * @generated
   */
  EAttribute getTraitement_Chemin();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl2.mML.Traitement#getEval <em>Eval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Eval</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement#getEval()
   * @see #getTraitement()
   * @generated
   */
  EReference getTraitement_Eval();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl2.mML.Traitement#getAlgo <em>Algo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Algo</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement#getAlgo()
   * @see #getTraitement()
   * @generated
   */
  EReference getTraitement_Algo();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl2.mML.Traitement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement#getName()
   * @see #getTraitement()
   * @generated
   */
  EReference getTraitement_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl2.mML.Traitement#getNames <em>Names</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Names</em>'.
   * @see org.xtext.example.mydsl2.mML.Traitement#getNames()
   * @see #getTraitement()
   * @generated
   */
  EReference getTraitement_Names();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see org.xtext.example.mydsl2.mML.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.mML.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.Algorithm <em>Algorithm</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Algorithm</em>'.
   * @see org.xtext.example.mydsl2.mML.Algorithm
   * @generated
   */
  EClass getAlgorithm();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.Algorithm#getLang <em>Lang</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lang</em>'.
   * @see org.xtext.example.mydsl2.mML.Algorithm#getLang()
   * @see #getAlgorithm()
   * @generated
   */
  EAttribute getAlgorithm_Lang();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl2.mML.Algorithm#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.mML.Algorithm#getName()
   * @see #getAlgorithm()
   * @generated
   */
  EReference getAlgorithm_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.StratEval <em>Strat Eval</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Strat Eval</em>'.
   * @see org.xtext.example.mydsl2.mML.StratEval
   * @generated
   */
  EClass getStratEval();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl2.mML.StratEval#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.mML.StratEval#getName()
   * @see #getStratEval()
   * @generated
   */
  EReference getStratEval_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.CrossValidation <em>Cross Validation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Cross Validation</em>'.
   * @see org.xtext.example.mydsl2.mML.CrossValidation
   * @generated
   */
  EClass getCrossValidation();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.CrossValidation#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl2.mML.CrossValidation#getNumber()
   * @see #getCrossValidation()
   * @generated
   */
  EAttribute getCrossValidation_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.TrainingTest <em>Training Test</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Training Test</em>'.
   * @see org.xtext.example.mydsl2.mML.TrainingTest
   * @generated
   */
  EClass getTrainingTest();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.TrainingTest#getNumber <em>Number</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number</em>'.
   * @see org.xtext.example.mydsl2.mML.TrainingTest#getNumber()
   * @see #getTrainingTest()
   * @generated
   */
  EAttribute getTrainingTest_Number();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.SVM <em>SVM</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>SVM</em>'.
   * @see org.xtext.example.mydsl2.mML.SVM
   * @generated
   */
  EClass getSVM();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.SVM#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl2.mML.SVM#getType()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_Type();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.SVM#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl2.mML.SVM#getName()
   * @see #getSVM()
   * @generated
   */
  EAttribute getSVM_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl2.mML.Tree <em>Tree</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tree</em>'.
   * @see org.xtext.example.mydsl2.mML.Tree
   * @generated
   */
  EClass getTree();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl2.mML.Tree#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Type</em>'.
   * @see org.xtext.example.mydsl2.mML.Tree#getType()
   * @see #getTree()
   * @generated
   */
  EAttribute getTree_Type();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl2.mML.Lang <em>Lang</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Lang</em>'.
   * @see org.xtext.example.mydsl2.mML.Lang
   * @generated
   */
  EEnum getLang();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl2.mML.SVMKernel <em>SVM Kernel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SVM Kernel</em>'.
   * @see org.xtext.example.mydsl2.mML.SVMKernel
   * @generated
   */
  EEnum getSVMKernel();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl2.mML.SVMType <em>SVM Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>SVM Type</em>'.
   * @see org.xtext.example.mydsl2.mML.SVMType
   * @generated
   */
  EEnum getSVMType();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl2.mML.Treetype <em>Treetype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Treetype</em>'.
   * @see org.xtext.example.mydsl2.mML.Treetype
   * @generated
   */
  EEnum getTreetype();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MMLFactory getMMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.TraitementImpl <em>Traitement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.TraitementImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTraitement()
     * @generated
     */
    EClass TRAITEMENT = eINSTANCE.getTraitement();

    /**
     * The meta object literal for the '<em><b>Chemin</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAITEMENT__CHEMIN = eINSTANCE.getTraitement_Chemin();

    /**
     * The meta object literal for the '<em><b>Eval</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAITEMENT__EVAL = eINSTANCE.getTraitement_Eval();

    /**
     * The meta object literal for the '<em><b>Algo</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAITEMENT__ALGO = eINSTANCE.getTraitement_Algo();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAITEMENT__NAME = eINSTANCE.getTraitement_Name();

    /**
     * The meta object literal for the '<em><b>Names</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRAITEMENT__NAMES = eINSTANCE.getTraitement_Names();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.VariableImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.AlgorithmImpl <em>Algorithm</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.AlgorithmImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getAlgorithm()
     * @generated
     */
    EClass ALGORITHM = eINSTANCE.getAlgorithm();

    /**
     * The meta object literal for the '<em><b>Lang</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ALGORITHM__LANG = eINSTANCE.getAlgorithm_Lang();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ALGORITHM__NAME = eINSTANCE.getAlgorithm_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.StratEvalImpl <em>Strat Eval</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.StratEvalImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getStratEval()
     * @generated
     */
    EClass STRAT_EVAL = eINSTANCE.getStratEval();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STRAT_EVAL__NAME = eINSTANCE.getStratEval_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.CrossValidationImpl <em>Cross Validation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.CrossValidationImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getCrossValidation()
     * @generated
     */
    EClass CROSS_VALIDATION = eINSTANCE.getCrossValidation();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CROSS_VALIDATION__NUMBER = eINSTANCE.getCrossValidation_Number();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.TrainingTestImpl <em>Training Test</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.TrainingTestImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTrainingTest()
     * @generated
     */
    EClass TRAINING_TEST = eINSTANCE.getTrainingTest();

    /**
     * The meta object literal for the '<em><b>Number</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRAINING_TEST__NUMBER = eINSTANCE.getTrainingTest_Number();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.SVMImpl <em>SVM</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.SVMImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVM()
     * @generated
     */
    EClass SVM = eINSTANCE.getSVM();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__TYPE = eINSTANCE.getSVM_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SVM__NAME = eINSTANCE.getSVM_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.impl.TreeImpl <em>Tree</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.impl.TreeImpl
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTree()
     * @generated
     */
    EClass TREE = eINSTANCE.getTree();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TREE__TYPE = eINSTANCE.getTree_Type();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.Lang <em>Lang</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.Lang
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getLang()
     * @generated
     */
    EEnum LANG = eINSTANCE.getLang();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.SVMKernel <em>SVM Kernel</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.SVMKernel
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVMKernel()
     * @generated
     */
    EEnum SVM_KERNEL = eINSTANCE.getSVMKernel();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.SVMType <em>SVM Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.SVMType
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getSVMType()
     * @generated
     */
    EEnum SVM_TYPE = eINSTANCE.getSVMType();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl2.mML.Treetype <em>Treetype</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl2.mML.Treetype
     * @see org.xtext.example.mydsl2.mML.impl.MMLPackageImpl#getTreetype()
     * @generated
     */
    EEnum TREETYPE = eINSTANCE.getTreetype();

  }

} //MMLPackage
