/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>SVM</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.mML.SVM#getType <em>Type</em>}</li>
 *   <li>{@link org.xtext.example.mydsl2.mML.SVM#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.mML.MMLPackage#getSVM()
 * @model
 * @generated
 */
public interface SVM extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl2.mML.SVMKernel}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.SVMKernel
   * @see #setType(SVMKernel)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getSVM_Type()
   * @model
   * @generated
   */
  SVMKernel getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.SVM#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.SVMKernel
   * @see #getType()
   * @generated
   */
  void setType(SVMKernel value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl2.mML.SVMType}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.SVMType
   * @see #setName(SVMType)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getSVM_Name()
   * @model
   * @generated
   */
  SVMType getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.SVM#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.SVMType
   * @see #getName()
   * @generated
   */
  void setName(SVMType value);

} // SVM
