/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.mML;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Training Test</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.mML.TrainingTest#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.mML.MMLPackage#getTrainingTest()
 * @model
 * @generated
 */
public interface TrainingTest extends StratEval
{
  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getTrainingTest_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.TrainingTest#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // TrainingTest
