/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.mML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Tree</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl2.mML.Tree#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl2.mML.MMLPackage#getTree()
 * @model
 * @generated
 */
public interface Tree extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl2.mML.Treetype}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.Treetype
   * @see #setType(Treetype)
   * @see org.xtext.example.mydsl2.mML.MMLPackage#getTree_Type()
   * @model
   * @generated
   */
  Treetype getType();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl2.mML.Tree#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see org.xtext.example.mydsl2.mML.Treetype
   * @see #getType()
   * @generated
   */
  void setType(Treetype value);

} // Tree
