/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MMLStandaloneSetup extends MMLStandaloneSetupGenerated {

	def static void doSetup() {
		new MMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
