/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl2.MMLRuntimeModule;
import org.xtext.example.mydsl2.MMLStandaloneSetup;
import org.xtext.example.mydsl2.ide.MMLIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MMLIdeSetup extends MMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    MMLRuntimeModule _mMLRuntimeModule = new MMLRuntimeModule();
    MMLIdeModule _mMLIdeModule = new MMLIdeModule();
    return Guice.createInjector(Modules2.mixin(_mMLRuntimeModule, _mMLIdeModule));
  }
}
