/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.ide;

import org.xtext.example.mydsl2.ide.AbstractMMLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MMLIdeModule extends AbstractMMLIdeModule {
}
