/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MMLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMMLWebModule extends DefaultWebModule {

}
