/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.web;

import org.xtext.example.mydsl2.web.AbstractMMLWebModule;

/**
 * Use this class to register additional components to be used within the web application.
 */
@SuppressWarnings("all")
public class MMLWebModule extends AbstractMMLWebModule {
}
