/**
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.web;

import com.google.inject.Injector;
import org.xtext.example.mydsl2.MMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages in web applications.
 */
@SuppressWarnings("all")
public class MMLWebSetup extends MMLStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nMMLIdeModule cannot be resolved.");
  }
}
