/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class MMLWebModule extends AbstractMMLWebModule {
}
