/*
 * generated by Xtext 2.16.0
 */
package org.xtext.example.mydsl2.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.example.mydsl2.services.MMLGrammarAccess;

@SuppressWarnings("all")
public class MMLSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MMLGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Traitement_VarPredictivesKeyword_7_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MMLGrammarAccess) access;
		match_Traitement_VarPredictivesKeyword_7_0_q = new TokenAlias(false, true, grammarAccess.getTraitementAccess().getVarPredictivesKeyword_7_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Traitement_VarPredictivesKeyword_7_0_q.equals(syntax))
				emit_Traitement_VarPredictivesKeyword_7_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'varPredictives'?
	 *
	 * This ambiguous syntax occurs at:
	 *     algo=Algorithm (ambiguity) (rule end)
	 *     name=Variable (ambiguity) (rule end)
	 */
	protected void emit_Traitement_VarPredictivesKeyword_7_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
